### ISSUE TITLE
iOS AutomationID

### ISSUE THREAD

**Issue by Pelinalpp** [lubiepomaranczki/XamForms.Controls.Calendar#14]
Hey,
Android has AutomationID. For example 10 January: NoResourceEntry-750 or NoResourceEntry-895 etc.
"NoResourceEntry-" part is constant. It chages only second part. And I use this in my uitests. But iOS has not any automation id.
Could you add automation id for ios, please?

**Comment by lubiepomaranczki** [comment]
Hey there 👋
for a better understanding can you please describe how you want to run your UI test? It will help people understand what needs to be done. 

Is there any chance you can implement it on your own and create a PR? I'm pretty busy right now and I won't promise it will happen soon. Unless someone else will pick it.

**Comment by lubiepomaranczki** [comment]
I am closing this issue. If you still have this problem, please reopen it.
