### ISSUE TITLE
Leap year issue?

### ISSUE THREAD

**Issue by broda02** [lubiepomaranczki/XamForms.Controls.Calendar#15]
The control seems to have an issue this year (leap year?).  This is my code:

XamForms.Controls.Calendar cal = new XamForms.Controls.Calendar
                    {
                        BorderWidth = options.BorderWidth,
                        BorderColor = System.Drawing.Color.DarkGray,
                        WeekdaysTextColor = System.Drawing.Color.White,
                        WeekdaysBackgroundColor = System.Drawing.Color.Brown,
                        TitleLabelTextColor = System.Drawing.Color.DarkGreen,
                        SelectedBorderColor = System.Drawing.Color.Yellow,
                        SelectedBackgroundColor = System.Drawing.Color.DodgerBlue,
                        SelectedTextColor = System.Drawing.Color.White,
                        BackgroundColor = options.BackgroundColour,
                        StartDay = DayOfWeek.Monday,
                        StartDate = DateTime.Now.AddMonths(-1),
                        ShowNumOfMonths = 2,
                        ShowInBetweenMonthLabels = true,
                        WidthRequest = common.Width / 3,
                        HeightRequest = common.Width / 3,
                        SelectedDate = DateTime.Now,
                    };

Here is the output for Feb and Mar that looks ok:

<img width="342" alt="Screenshot 2020-03-14 at 09 41 57" src="https://user-images.githubusercontent.com/13601553/76679544-58c78200-65d9-11ea-8282-dba42dfd6971.png">

But if I go back then Dec and Jan are wrong (1st Jan was Wednesday etc)

<img width="342" alt="Screenshot 2020-03-14 at 09 42 18" src="https://user-images.githubusercontent.com/13601553/76679556-6a108e80-65d9-11ea-922c-494662b1d2bf.png">

**Comment by lubiepomaranczki** [comment]
Hey @broda02 🙌,
I've tried [reproducing your issue](https://github.com/lubiepomaranczki/XamForms.Controls.Calendar/tree/%2315-issue-test) in the playground and I can't see it. Could you please fork the code (branch #15-issue-test) and adjust the code so the issue can be seen? Without it, it might be hard to check what is wrong

**Comment by lubiepomaranczki** [comment]
If you still have this issue, please reopen this one. I am closing this one
