### ISSUE TITLE
The amount of DateTime in SelectedDates doubled after each click

### ISSUE THREAD

**Issue by rbennum** [lubiepomaranczki/XamForms.Controls.Calendar#16]
Hello. First of all, I would like to say thank you for maintaining this library. This is my first Xamarin project and I happen to use this library.

So, I found out that every time I clicked the CalendarButton on a MultiSelectDates mode calendar, the content of SelectedDates would double by the same value (ex: I click on 23 March 2020, then there would be two 23 March 2020s inside SelectedDates). Does it really how it should be?

Thank you.

**Comment by lubiepomaranczki** [comment]
Hey there 👋 
I am not sure how @rebeccaXam designed it to work like. I think that with that option enabled you should receive a unique list of selected dates. What is your opinion on that one?

**Comment by lubiepomaranczki** [comment]
Ok, I've reproduced it and I can see what you are talking about.
definitely a bug!

**Comment by lubiepomaranczki** [comment]
This should be fixed in [package version 1.2.2](https://www.nuget.org/packages/XamForms.Enhanced.Calendar/1.2.2). Please check if it works. If not, feel free to write a comment. Otherwise, I will close this issue tomorrow

**Comment by rbennum** [comment]
Hello. I am sorry for the long response, it was the end of my shift. I just checked the newest version of the library and I would say the bug has been fixed. Thank you so much.

**Comment by lubiepomaranczki** [comment]
No problem. Closing it.
