### ISSUE TITLE
Unable to resolve assembly error

### ISSUE THREAD

**Issue by lrolleman** [lubiepomaranczki/XamForms.Controls.Calendar#3]
When I add the project from nuget, all the xaml files complain (even if they don't reference it...) that it is unable to resolve the assembly "XamForms.Controls.Calendar"

When I check the nuget packages folder, the .netstandard library does not have that dll (just XamForms.Enhanced.dll)

**Comment by lubiepomaranczki** [comment]
Sorry for missing your question!
Indeed I can confirm there is an error in nuget package.

I am just fixing it so hold on!

**Comment by lubiepomaranczki** [comment]
@lrolleman this should be fixed in `ver. 1.2.1`. Please take a look and reopen this issue if it still happens.

Thanks for letting me know! 🚀
