### ISSUE TITLE
Title arrow issues?

### ISSUE THREAD

**Issue by ChrisZi** [lubiepomaranczki/XamForms.Controls.Calendar#36]
Hi,
I trying to change titleLeftArrow and titleRightArrow:

TitleLeftArrowImage="left.png" 
TitleRightArrowImage="right.png"

New images show up, but old (red arrows) are still visible.
How replace default arrows?

**Comment by lubiepomaranczki** [comment]
Hey @ChrisZi ,
default arrows are text. You can force it to be empty. Not the best approach but should do the trick
```
TitleLeftArrowImage="left.png"
TitleRightArrowImage="right.png"
TitleLeftArrowText=""
TitleRightArrowText=""
```
Please let me know if it worked. It it didn't, please reopen this issue

**Comment by ChrisZi** [comment]
It worked.
Thank you for your help.
Regards!
