### ISSUE TITLE
Is there a way i can unselect the current selected date

### ISSUE THREAD

**Issue by danypepin1** [lubiepomaranczki/XamForms.Controls.Calendar#39]
I saw that if you have MultiSelectedDates to true, you can use SelectedDates to unselect so i could do calendar.SelectedDates.Clear() and it would work but my problem is that i don't have SelectedDates set to true.

Here i have MultiSelectedDates to false, and even if i set SelectedDate to null, the Date still has a selected border and is still selected. Is there a way with your plugin to clear the selected date?

 I need it for my app, because when the Calendar page is loaded, it always keeps the Date u selected before selected, which i don't want ?

Is there a way to do that ? Thanks a lot !

**Comment by lubiepomaranczki** [comment]
Sorry for closing the issue 😇

Could you try installing `1.5.1-alpha`? 

With that version, you should be able to do
`SelectedDate=null`
and it should reset the selected date.

Please, let me know if it works and if you have any questions

**Comment by danypepin1** [comment]
It turns out that i could use SelectedDates.Clear(); even if i didn't touch MultiSelectedDates, so everything works fine now. Sorry for disturbing and thanks  a lot for this plugin :)

**Comment by lubiepomaranczki** [comment]
True. If you want, within 1.5.1-alpha you can also set SelectedDate to null and it should work.

Glad that you got it fixed!

Closing this issue 🔥
