### ISSUE TITLE
Importing firebase data into the Special Date parameter

### ISSUE THREAD

**Issue by developersimsek** [lubiepomaranczki/XamForms.Controls.Calendar#4]
Hello there,
I'm sorry, I've looked at open issues, but I can't find a solution to my problem.
What I want to do; Importing the dates in the firebase database to SpecialDates. I successfully retrieve data from Firebase, but I cannot import it to the calendar. I tried this with the following method, but I didn't succeed. I would be glad if you help. Thanks in advance ...

Xaml source
```xaml
<controls:Calendar
    Padding="10,0,10,0"
    SelectedBorderWidth="4"
    DisabledBorderColor="Black"
    ShowNumberOfWeek="false"
    StartDay="Monday"
    TitleLabelTextColor="Purple"
    DateClicked="Calendar_DateClicked"
    x:Name="calender"
    BindingContext="{Binding Tarih}" 
    WeekdaysShow="True"
    WeekdaysFontAttributes="Bold"
    EnableTitleMonthYearView="True"
    TitleLeftArrowTextColor="Blue"
    SelectedDate="{Binding Date}"
    SpecialDates="{Binding Tarih}"
    DateCommand="{Binding DateChosen}" >
</controls:Calendar>
```

Code behind:
```csharp
public Detail()
{
    InitializeComponent();
    DBFire data;
    data = new DBFire();
    Device.BeginInvokeOnMainThread(async () =>
    {
        calender.BindingContext = await data.GetList();
    });
}

**Comment by mimunoz** [comment]
Hi, 
Tarih it's a Collection? because you should have a ObservableCollection binding SpecialDates from your ViewModel and your dates from Firebase in SpecialDate format. 
ex.
`SpecialDates = new ObservableCollection<XamForms.Controls.SpecialDate>();`

Regards!

**Comment by lubiepomaranczki** [comment]
Gosh! Sorry, I don't how I've missed this question. @developersimsek please answer @mimunoz, so we can investigate more

@mimunoz thanks for answering!

**Comment by developersimsek** [comment]
Hi, Thanks for the answer @mimunoz  and @lubiepomaranczki Sorry, I'm late in researching the method in the answer. But I did not succeed. Normally I list the firebase data with the following method and it is reflected correctly. But I have no idea how to get it with ObservableCollection. Can you help with this? I can also add SpecialDates with ObservableCollection in this way. What I want is to get SpecialDate data from the firebase. Thanks in advance for the answers.


**The block from which I correctly retrieved data from Firebase**
    public async Task<List<Items>> Deneme()
        {
            var liste = (await client
              .Child("Tarih")
              .OnceAsync<Items>())
              .Select(item =>
              new Items
              {
                  Tarih = item.Object.Tarih
              }
              ).ToList();

            return liste;
        }


**This way I can add Manual SpecialDates with ObservableCollection.**

    calender.SpecialDates = new ObservableCollection<XamForms.Controls.SpecialDate>()
            {
                                    new SpecialDate(new DateTime(2019, 08, 26)){ BackgroundColor = Color.Red, TextColor = Color.White, BorderColor = Color.DarkBlue, BorderWidth=3, Selectable = true }
            };

**Comment by lubiepomaranczki** [comment]
You need to somehow parse the `List<Items>` to `ObservableCollection<XamForms.Controls.SpecialDate>`
```csharp
var dates = new ObservableCollection<XamForms.Controls.SpecialDate>();
foreach(var item in liste)
{
    dates.Add(new SpecialDate(new DateTime(item.Year, item.Month, item.Day));
}
```
then you need to assign it to Calendar special dates
```csharp
SpecialDates = dates;
```

**Comment by developersimsek** [comment]
Hi,
As you passed, I implemented the following, but the values ​​did not return. Can you give a detailed example from Firebase to add a custom date to the calendar? If you want, we can share the project and go through it? Thank you for your answer...

  public async Task<List<Items>> Deneme()
        {
            var liste = (await client
              .Child("Tarih")
              .OnceAsync<Items>())
              .Select(item =>
              new Items
              {
                  Tarih = item.Object.Tarih
              }
              ).ToList();
            var dates = new ObservableCollection<XamForms.Controls.SpecialDate>();
            foreach (var item in liste)
            {
                dates.Add(new SpecialDate(new DateTime(item.Tarih.Year, item.Tarih.Month, item.Tarih.Day)));
            }
            calender.SpecialDates = dates;
            return liste;
        }

**Comment by developersimsek** [comment]
Hello, Many Thanks for your answers. The problem is resolved as follows. @lubiepomaranczki  @mimunoz 
```
 public async void ListDate(List<Items> list)
        {
            var liste = (await client
                         .Child("Tarih")
                         .OnceAsync<Items>())
                         .Select(item =>
                         new Items
                         {
                             Tarih = item.Object.Tarih
                         }
                         ).ToList();
            var dates = new ObservableCollection<XamForms.Controls.SpecialDate>();
            foreach (var item in liste)
            {
                dates.Add(new SpecialDate(new DateTime(item.Tarih.Year, item.Tarih.Month, item.Tarih.Day)) { Selectable = true, BackgroundColor = Color.LightGreen, TextColor = Color.Black, FontSize = 20, BorderWidth = 3, BorderColor = Color.Red });
            }
            calender.SpecialDates = dates;
        }
```

**Comment by lubiepomaranczki** [comment]
Great! Good to hear that you’ve solved the issue.
