### ISSUE TITLE
To display only dates of current month

### ISSUE THREAD

**Issue by rushabhshah97** [lubiepomaranczki/XamForms.Controls.Calendar#48]
Hi ,

I want to make the dates outside current month to be invisble.(The dates that are underlined in RED) Kindly help.

<img width="373" alt="35143849-bef99a7a-fd28-11e7-9435-8d20db89016d" src="https://user-images.githubusercontent.com/48272994/116660484-bae77000-a9b0-11eb-94e8-dd523ec703b0.png">

**Comment by laxman4434** [comment]
Hi,

I have the same issue. Any help would be appreciated.

**Comment by mimunoz** [comment]
Hi, you can use **DatesTextColorOutsideMonth** property, to set white or transparent color to hide it.

**Comment by lubiepomaranczki** [comment]
@laxman4434, @rushabhshah97 did Miguel's solution helped you or do you need further assistance?

**Comment by laxman4434** [comment]
> Hi, you can use **DatesTextColorOutsideMonth** property, to set white or transparent color to hide it.

HI @mimunoz , thanks for you reply.

My requirement is to disable the dates before current date. I am setting the current date as MinDate. Also I am enabling and disabling few dates based on my API response and I am using Special Date feature.

Setting the **DatesTextColorOutsideMonth** to "Transparent or white" does not work in this scenario. If I remove both MinDate and Special Dates option, then it works. But still it leaves bit of gap at the end.

**Comment by lubiepomaranczki** [comment]
@laxman4434 sorry, I don't quite understand your issue. Is it possible that you can create/share repository demonstrating the issue?

**Comment by laxman4434** [comment]
> @laxman4434, @rushabhshah97 did Miguel's solution helped you or do you need further assistance?

Hi @lubiepomaranczki ,

Thanks for your response. That suggestion does not work for me.

Following is the way that I implemented the calendar

```
<controls:Calendar Padding="10,0,10,0" ShowNumberOfWeek="false" StartDay="Monday" BackgroundColor="Transparent" TitleLabelTextColor="#000000"
          TitleLeftArrowTextColor="#007AFF" TitleRightArrowTextColor="#007AFF" TitleRightArrowText=">" TitleLeftArrowText="&lt;" SelectedDate="{Binding SelectedDate}"
          SpecialDates="{Binding AvailableDates}" DateCommand="{Binding DateChosenCommand}" BorderWidth="0" BorderColor="Transparent" DisabledBackgroundColor="Transparent"
          DisabledBorderWidth="0" DisabledTextColor="#949494" OuterBorderWidth="0" MinDate="{Binding MinimumDate}" SelectedBorderWidth="0" DatesTextColorOutsideMonth="Transparent"
          DatesBackgroundColorOutsideMonth="Transparent">
```

C# code to load dates:

```
AvailableDates.Add( new SpecialDate( date )
{
Selectable = availableDate,
BackgroundColor = ( date == DateTime.Now ) ? Color.FromHex( "#d8ebff" ) : Color.White,
TextColor = availableDate ? Color.Black : Color.FromHex( "#949494" ),
BorderWidth = 0,
BorderColor = Color.Transparent
} ); 

```
This is the output that i get

![image](https://user-images.githubusercontent.com/7378501/122669838-6fa84b80-d202-11eb-96d3-2585df6c6a25.png)

**Comment by laxman4434** [comment]
```
AvailableDates.Add( new SpecialDate( date )
{
Selectable = availableDate,
BackgroundColor = ( date == DateTime.Now ) ? Color.FromHex( "#d8ebff" ) : Color.White,
//TextColor = availableDate ? Color.Black : Color.FromHex( "#949494" ),
BorderWidth = 0,
BorderColor = Color.Transparent
} ); 
```

If I comment out the text color line of code, this is the out put I get.

![image](https://user-images.githubusercontent.com/7378501/122670302-a7b08e00-d204-11eb-8c71-85eca5091998.png)

but disabled dates are also being shown as enabled. Also, the previous month dates are still being shown.

**Comment by mimunoz** [comment]
Hi, so @laxman4434  your issue it's not **hide dates outside the current month** how @rushabhshah97  asked. You need hide dates what aren't in special dates and before dates right? Can you provide a project sample please?

Regards

**Comment by lubiepomaranczki** [comment]
@laxman4434, I've pushed new version of NuGet. Please check **1.6.1-alpha** and try setting `HideSpecialOutOfMonth` to true. 

Special dates out of month should disappear. Let me know if it's what you want

**Comment by laxman4434** [comment]
Hi @lubiepomaranczki , thank you very much your response and setting `HideSpecialOutOfMonth `to true along with `DatesBackgroundColorOutsideMonth="White"` and `DatesTextColorOutsideMonth="White" `actually solved my issue.

I really appreciate your help.

**Comment by lubiepomaranczki** [comment]
as @rushabhshah97 is not replying any more I am gonna close the issue. 

@laxman4434 if you have troubles with the package please open another issue 👨‍💻

**Comment by laxman4434** [comment]
Only issue, I have now is Android, I see border lines like below.

![Android Calendar](https://user-images.githubusercontent.com/7378501/124719672-bc9e5880-df4a-11eb-8d1d-0012b88c2a16.PNG)

Where as iOS is very clean.

<img width="280" alt="iOS Calendar" src="https://user-images.githubusercontent.com/7378501/124719744-cde76500-df4a-11eb-93b5-bb403726f78e.png">

I was wondering if there is any option like `DatesBorderColorOutsideMonth`, to get rid of those borders for dates outside month

**Comment by lubiepomaranczki** [comment]
Please open another issue as this is a different bug.
